### ISSUE TITLE
Is there conflict with Ignore and Flags in codecov

### ISSUE THREAD

**Issue by doublnt** [codecov/codecov-bash#167]
```yaml
flags:
  unittest:
    # only test unittests
    paths:
      - net-core.Tests/
  featuretest:
    # only test featuretest
    paths:
      - net-feature-test/

ignore:
  - "net-core.Tests/" 
  - "sdk-feature-test/"  
```

why the result does not show the flag reports? 
and how can i ignore test code? use ignore attributes?
