### ISSUE TITLE
codecov/patch is failing although the coverage has increased

### ISSUE THREAD

**Issue by tamj0rd2** [codecov/codecov-bash#299]
[Here's one affected PR](https://github.com/tamj0rd2/ncdc/pull/175), although I've noticed this issue for the past week now.

![image](https://user-images.githubusercontent.com/20561445/81866236-d1f63d80-9566-11ea-977a-a3a341b17017.png)

My [codecov.yml](https://github.com/tamj0rd2/ncdc/blob/master/codecov.yml) has a 0% threshold so I'm not sure why this is happening or what's causing it

```yml
coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        paths:
          - "src"
        # advanced
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: False
        only_pulls: false
```
