### ISSUE TITLE
Failing upload for public repo using GitHub Actions

### ISSUE THREAD

**Issue by rowanseymour** [codecov/codecov-bash#393]
`ERROR: Tokenless uploads are only supported for public repositories on GitHub Actions that can be verified through the Actions API.` 

Was working fine, and as you can see it's a public repo

https://github.com/nyaruka/rapidpro/pull/3122/checks?check_run_id=1553406479

Github action is

```
- name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
```
