### ISSUE TITLE
Codecov failure: Bash script checksums do not match published values. Please contact security@codecov.io immediately.

### ISSUE THREAD

**Issue by spencercjh** [codecov/codecov-bash#435]
I used Github Action as the environment for my project CI/CD env, using [codecov-action](https://github.com/codecov/codecov-action) to upload codecov report, and I got this error **today**:

![image](https://user-images.githubusercontent.com/29922079/119461139-fe47bb00-bd71-11eb-9220-d2a71fa8fe0e.png)

I'm not quite sure if the issue is raised here or in that github action repo. I've been using the suit normally for over a month now.

```yaml
- name: Report Codecov
  uses: codecov/codecov-action@v1.4.1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    files: ./build/reports/jacoco/test/jacocoTestReport.xml
    fail_ci_if_error: false
    verbose: true
```
